name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Installer les dépendances
        run: uv sync --all-extras --dev
      - name : Linter
        run : uvx run ruff check
      - name : Formatter
        run : uvx run ruff format --check
      - name: Exécution des tests (Pytest)
        run: uv run python3 -m pytest

  build:
    name: Verify Docker Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t credit-scoring-api .
